services:
  elasticsearch-index-creator:
    container_name: elastic_dump_loader
    image: elastic_dump_loader
    build:
      context: .
      dockerfile: docker/elastic-dump-loader.Dockerfile
    env_file:
      - .env