services:
  db:
    scale: 0

  etl:
    scale: 0

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    ports:
      - "6379:6379"

  app_server:
    container_name: app_server
    image: app_server
    restart: no
    expose:
      - "9090"
    build:
      context: .
      dockerfile: ./fastapi_service/Dockerfile
    env_file:
      - .env
    depends_on:
      venv_builder:
        condition: service_completed_successfully
      elasticsearch-index-creator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]

  elasticsearch-index-creator:
    depends_on:
      python_base:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy

  functional_tests:
    container_name: functional_tests
    image: functional_tests
    build:
      context: .
      dockerfile: tests/functional/Dockerfile
    env_file:
      - .env
    depends_on:
      app_server:
        condition: service_started
