"""add default roles

Revision ID: d21fb1cebd5a
Revises: 4a6b982b5d53
Create Date: 2024-06-13 23:53:05.875798

"""

from typing import Sequence, Union

from alembic import op

from auth_service.src.core.config import settings as cfg
from auth_service.src.models import Role

# revision identifiers, used by Alembic.
revision: str = "d21fb1cebd5a"
down_revision: Union[str, None] = "4a6b982b5d53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        table=Role.__table__,
        rows=[
            cfg.rbac.default.model_dump(),
            cfg.rbac.admin.model_dump(),
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE auth.role CASCADE")
    # ### end Alembic commands ###
