"""add id into user_role, update ondelete actions

Revision ID: bb34c3ada8fe
Revises: 182490d14cc0
Create Date: 2024-06-06 10:41:57.260732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb34c3ada8fe"
down_revision: Union[str, None] = "182490d14cc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("login_history_user_id_fkey", "login_history", type_="foreignkey")
    op.create_foreign_key(
        None,
        "login_history",
        "user",
        ["user_id"],
        ["id"],
        source_schema="auth",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    op.add_column("user_role", sa.Column("id", sa.Uuid(), nullable=False))
    op.drop_constraint("user_role_user_id_fkey", "user_role", type_="foreignkey")
    op.drop_constraint("user_role_role_id_fkey", "user_role", type_="foreignkey")
    op.create_foreign_key(
        None, "user_role", "role", ["role_id"], ["id"], source_schema="auth", referent_schema="auth", ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_role", "user", ["user_id"], ["id"], source_schema="auth", referent_schema="auth", ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_role", schema="auth", type_="foreignkey")
    op.drop_constraint(None, "user_role", schema="auth", type_="foreignkey")
    op.create_foreign_key("user_role_role_id_fkey", "user_role", "role", ["role_id"], ["id"])
    op.create_foreign_key("user_role_user_id_fkey", "user_role", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_column("user_role", "id")
    op.drop_constraint(None, "login_history", schema="auth", type_="foreignkey")
    op.create_foreign_key(
        "login_history_user_id_fkey", "login_history", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
