"""add permissions

Revision ID: e4f8646ab816
Revises: 8f2d0da2262e
Create Date: 2024-06-14 02:25:44.499650

"""

from typing import Sequence, Union

from alembic import op

from auth_service.src.core.default_user_roles import DefaultPermission, PermissionLevel
from auth_service.src.models import Permission
from auth_service.src.utils.static_uuid import get_static_uuid

# revision identifiers, used by Alembic.
revision: str = "e4f8646ab816"
down_revision: Union[str, None] = "8f2d0da2262e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permissions = [
        {"name": "/healthcheck", "description": "Api health check", "level": PermissionLevel.NONE},
        {"name": "/user/signup", "description": "User signup", "level": PermissionLevel.NONE},
        {"name": "/user/login", "description": "User login", "level": PermissionLevel.NONE},
        {"name": "/user/logout", "description": "User logout", "level": PermissionLevel.READ},
        {"name": "/user/refresh", "description": "Refresh token pair", "level": PermissionLevel.WRITE},
        {"name": "/user/history", "description": "Retrieve authentication history", "level": PermissionLevel.READ},
        {"name": "/user/password_update", "description": "Change password", "level": PermissionLevel.WRITE},
        {"name": "/user/role/assign", "description": "Assign role", "level": PermissionLevel.ADMIN},
        {"name": "/user/role/revoke", "description": "Revoke role", "level": PermissionLevel.ADMIN},
        {"name": "/user/role/verify", "description": "Verify user role", "level": PermissionLevel.ADMIN},
        {"name": "/role/create", "description": "Create role", "level": PermissionLevel.ADMIN},
        {"name": "/role/delete", "description": "Delete role", "level": PermissionLevel.ADMIN},
        {"name": "/role/list", "description": "View all roles", "level": PermissionLevel.READ},
        {"name": "/role/update", "description": "Update user role", "level": PermissionLevel.ADMIN},
    ]
    rows = []
    for permission in permissions:
        rows.append(
            DefaultPermission(
                id=get_static_uuid(permission["name"]),
                name=permission["name"],
                level=permission["level"],
                description=permission["description"],
            ).model_dump()
        )
    op.bulk_insert(table=Permission.__table__, rows=rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE auth.permission CASCADE")
    # ### end Alembic commands ###
