"""add user and role

Revision ID: 72a7fb9d3426
Revises: 
Create Date: 2024-06-04 04:43:41.048693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a7fb9d3426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('login_history_user_id_fkey', 'login_history', type_='foreignkey')
    op.create_foreign_key(None, 'login_history', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], source_schema='auth', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'user_role', schema='auth', type_='foreignkey')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'login_history', schema='auth', type_='foreignkey')
    op.create_foreign_key('login_history_user_id_fkey', 'login_history', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
