"""add role_permissions

Revision ID: 75cc9bed03c0
Revises: e4f8646ab816
Create Date: 2024-06-14 02:49:39.915355

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from auth_service.src.core.config import settings as cfg
from auth_service.src.models import Permission, RolePermission

# revision identifiers, used by Alembic.
revision: str = "75cc9bed03c0"
down_revision: Union[str, None] = "e4f8646ab816"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    permissions = session.query(Permission.id, Permission.level).all()

    role_permission = []
    for permission in permissions:
        id_, level = permission
        role_permission.append(
            {
                "role_id": cfg.rbac.admin.id,
                "permission_id": id_,
            }
        )

        if level < 11:
            role_permission.append(
                {
                    "role_id": cfg.rbac.default.id,
                    "permission_id": id_,
                }
            )

    op.bulk_insert(table=RolePermission.__table__, rows=role_permission)

    session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE auth.role_permission CASCADE")
    # ### end Alembic commands ###
