"""add superuser

Revision ID: 8f2d0da2262e
Revises: d21fb1cebd5a
Create Date: 2024-06-14 00:47:50.765174

"""

from typing import Sequence, Union

from alembic import op

from auth_service.src.core.config import settings as cfg
from auth_service.src.models import User, UserRole
from auth_service.src.schemas.request import AdminCreate, UserRoleCreate

# revision identifiers, used by Alembic.
revision: str = "8f2d0da2262e"
down_revision: Union[str, None] = "d21fb1cebd5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admin = AdminCreate(
        email=cfg.su.email,
        username=cfg.su.username,
        password=cfg.su.password,
    )
    op.bulk_insert(
        table=User.__table__,
        rows=[
            admin.model_dump(),
        ],
    )

    op.bulk_insert(
        table=UserRole.__table__,
        rows=[
            UserRoleCreate(user_id=admin.id, role_id=cfg.rbac.admin.id).model_dump(),
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE auth.user CASCADE")
    # ### end Alembic commands ###
